[package]
name = "rusty-kans"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["ws", "macros"] }
sqlx = { version = "0.9", features = ["sqlite", "runtime-tokio", "macros", "migrate"] }
askama = "0.16.0"
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["fs"] }
tower-sessions = "0.15"
tower-sessions-redis-store = {
    git = "https://github.com/maxcountryman/tower-sessions-stores",
}
oauth2 = "5"
dotenvy = "0.15"
reqwest = { version = "0.13", features = ["json"] }
dashmap = "6"
sha2 = "0.10"
garde = "0.23"

[dev-dependencies]
test-case = "3"
axum-test = "21"