CREATE TABLE IF NOT EXISTS boards (
    board_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS lists (
    list_id INTEGER PRIMARY KEY,
    board_id INTEGER,
    name TEXT NOT NULL,

    FOREIGN KEY (board_id) REFERENCES boards(board_id) ON DELETE CASCADE ON UPDATE NO ACTION
)

CREATE TABLE IF NOT EXISTS cards (
    card_id INTEGER PRIMARY KEY,
    list_id INTEGER,
    title TEXT NOT NULL,
    description TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Todo',

    FOREIGN KEY (list_id) REFERENCES lists(list_id) ON DELETE CASCADE ON UPDATE NO ACTION
)